version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    command: bash -c 'npm run dev'
    depends_on:
      - database
    env_file: .env
    networks:
      - growth
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_test
    command: bash -c 'npm run test'
    depends_on:
      - database
    env_file: .env.sample
    networks:
      - growth
    volumes:
      - .:/app

  database:
    container_name: database
    image: mongo
    networks:
      - growth
    ports:
      - 27017:27017
    volumes:
      - database-volume:/data/db

networks:
  growth:

volumes:
  database-volume:
