version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    env_file: .env
    depends_on:
      - database
    volumes:
      - .:/home/node/app
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - database-volume:/data/db
volumes:
  database-volume:
