version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-${NODE_ENV}
    container_name: backend
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
    env_file: .env
    depends_on:
      - database
    volumes:
      - .:/home/node/app
  database:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - database-volume:/data/db
volumes:
  database-volume:
